"""
Flask Application - CIS Report API
Handles HTML and PDF format requests
"""

from flask import Flask, jsonify, request, send_file
from flask_cors import CORS
import io
import logging

# Import PDF generator
from pdf_generator import PDFGenerator

# Initialize Flask
app = Flask(__name__)

# CORS Configuration
ALLOWED_ORIGINS = [
    "https://rpr-verify-b.web.app",
    "https://verify.rprcomms.com",
    "https://rprcomms.com",
    "https://rpr-verify-et8hakpyt-butterdime.vercel.app",
    "http://localhost:4200"
]

CORS(app, resources={r"/*": {"origins": ALLOWED_ORIGINS}})

# Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ============================================================================
# MOCK IMPLEMENTATIONS (Issue 2 resolved - for testing without real Firestore)
# ============================================================================

class MockReportGenerator:
    """Mock report generator for testing"""
    
    def analyze_case(self, case_data):
        """Mock analysis"""
        return {
            'case_id': case_data.get('id', 'UNKNOWN'),
            'status': 'analyzed',
            'proof_of_identity': {'score': 0.95},
            'proof_of_address': {'score': 0.88},
            'business_details': {'score': 0.92},
            'source_of_funds': {'score': 0.90}
        }
    
    def generate_human_readable(self, report_data):
        """Generate mock HTML report"""
        case_id = report_data.get('case_id', 'UNKNOWN')
        return f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CIS Report - {case_id}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
        }}
        h1 {{
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        .section {{
            margin: 20px 0;
            padding: 15px;
            background: #f8f9fa;
            border-left: 4px solid #3498db;
        }}
        .score {{
            font-weight: bold;
            color: #27ae60;
        }}
    </style>
</head>
<body>
    <h1>Customer Information Sheet</h1>
    <p><strong>Case ID:</strong> {case_id}</p>
    <p><strong>Generated:</strong> December 13, 2025</p>
    
    <div class="section">
        <h2>Proof of Identity</h2>
        <p class="score">Confidence Score: 95%</p>
        <p>Identity documents verified and authenticated.</p>
    </div>
    
    <div class="section">
        <h2>Proof of Address</h2>
        <p class="score">Confidence Score: 88%</p>
        <p>Address documents validated against external databases.</p>
    </div>
    
    <div class="section">
        <h2>Business Details</h2>
        <p class="score">Confidence Score: 92%</p>
        <p>Business registration and corporate structure verified.</p>
    </div>
    
    <div class="section">
        <h2>Source of Funds</h2>
        <p class="score">Confidence Score: 90%</p>
        <p>Fund origins traced and documented.</p>
    </div>
    
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; color: #666;">
        <p>This is a mock report for testing purposes.</p>
        <p>Report generated by RPR-VERIFY Compliance System</p>
    </footer>
</body>
</html>
        """


def get_case_from_firestore_mock(case_id: str):
    """Mock Firestore retrieval"""
    # In production, replace with real Firestore call
    logger.info(f"📋 Mock: Fetching case {case_id} from Firestore")
    return {
        'id': case_id,
        'client_name': 'Test Client',
        'status': 'active'
    }


# ============================================================================
# API ENDPOINTS
# ============================================================================

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint"""
    return jsonify({'status': 'healthy', 'python': '3.11', 'playwright': 'installed'}), 200


@app.route('/api/reports/cis/<case_id>', methods=['GET'])
def get_cis_report(case_id):
    """
    CIS Report Endpoint - Supports HTML and PDF formats
    
    Query Parameters:
        format: 'html' (default) or 'pdf'
    
    Returns:
        - HTML format: JSON with summary_text (HTML string)
        - PDF format: Binary PDF file
    """
    
    try:
        # Get format parameter (default: html)
        output_format = request.args.get('format', 'html').lower()
        
        logger.info(f"📊 Generating CIS report for case: {case_id}, format: {output_format}")
        
        # Fetch case data (MOCK - Issue 2 resolved)
        case_data = get_case_from_firestore_mock(case_id)
        
        if not case_data:
            return jsonify({
                'status': 'error',
                'message': f'Case {case_id} not found'
            }), 404
        
        # Generate report structure (MOCK)
        report_generator = MockReportGenerator()
        report_data = report_generator.analyze_case(case_data)
        
        # Generate HTML
        html_content = report_generator.generate_human_readable(report_data)
        
        # Handle format request
        if output_format == 'pdf':
            # NEW: Server-side PDF generation
            logger.info(f"🎨 Generating PDF using Playwright...")
            
            pdf_generator = PDFGenerator()
            pdf_bytes = pdf_generator.generate_pdf_from_html(html_content)
            
            # Return PDF binary
            return send_file(
                io.BytesIO(pdf_bytes),
                mimetype='application/pdf',
                as_attachment=True,
                download_name=f'CIS_Report_{case_id}.pdf'
            )
        
        else:
            # DEFAULT: Return HTML in JSON (backward compatible)
            return jsonify({
                'status': 'success',
                'case_id': case_id,
                'summary_text': html_content,
                'sections': report_data
            }), 200
    
    except Exception as e:
        logger.error(f"❌ Error generating report: {str(e)}")
        return jsonify({
            'status': 'error',
            'message': 'Internal server error'
        }), 500


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
