# -*- coding: utf-8 -*-
"""Google Drive Utilities

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBMOu-QXCaeF5nkH4V8g9ukOatjmg-6q
"""

import os
import logging
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import google.auth
from google.auth.transport.requests import Request
from googleapiclient.http import MediaIoBaseUpload
import io
from typing import Dict, Any

logger = logging.getLogger(__name__)

# --- CRITICAL FIX: Environment Variable Fallback Chain ---
MASTER_FOLDER_ID = (
    os.environ.get('DRIVE_PARENT_FOLDER_ID') or
    os.environ.get('RPR_DRIVE_MASTER_FOLDER_ID') or
    os.environ.get('DRIVE_MASTER_FOLDER_ID')
) or None  # Use None instead of mock fallback - allows root Drive location

def get_drive_service():
    """Builds and returns the Google Drive API service with detailed diagnostic logging."""
    try:
        creds, project = google.auth.default(
            scopes=['https://www.googleapis.com/auth/drive.file', 'https://www.googleapis.com/auth/drive']
        )

        # Diagnostic Log 1: Identity Check
        logger.info(f"🛠️ get_drive_service called. Project: {project}")
        if hasattr(creds, 'service_account_email'):
            logger.info(f"👤 Auth Method: Service Account ({creds.service_account_email})")
        else:
            logger.info("👤 Auth Method: User/Default Credentials")

        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())

        service = build('drive', 'v3', credentials=creds)
        return service
    except Exception as e:
        logger.error(f"❌ Failed to initialize Google Drive service: {e}")
        return None

def create_job_folder_in_drive(report_id: str) -> str:
    """Creates a dedicated Google Drive folder with diagnostic logging."""
    # Diagnostic Log 2: Folder Target Check
    logger.info(f"📌 Using PARENT_FOLDER_ID: {MASTER_FOLDER_ID or 'ROOT (none specified)'}")

    drive_service = get_drive_service()
    if not drive_service:
        raise Exception("Failed to connect to Google Drive service.")

    file_metadata = {
        'name': report_id,
        'mimeType': 'application/vnd.google-apps.folder',
        'parents': [MASTER_FOLDER_ID] if MASTER_FOLDER_ID else []  # Empty list = root Drive
    }

    try:
        logger.info(f"🚀 Sending Drive API request to create folder: {report_id}")
        folder = drive_service.files().create(body=file_metadata, fields='id, name').execute()
        logger.info(f"✅ Folder created successfully. ID: {folder.get('id')}")
        return folder.get('id')
    except HttpError as e:
        # Diagnostic Log 3: Error Capture
        error_content = e.content.decode()
        logger.error(f"❌ Drive API call failed: {error_content}")
        raise HttpError(e.resp, f"Drive API Error: {error_content}".encode('utf-8'))
    except Exception as e:
        logger.error(f"❌ Unexpected error in folder creation: {e}")
        raise Exception(f"Internal error during Drive operation: {e}")

def upload_document_to_folder(folder_id: str, file_data: bytes, filename: str, mimetype: str) -> Dict[str, Any]:
    """Uploads a file to the specified Google Drive folder."""
    drive_service = get_drive_service()
    if not drive_service:
        raise Exception("Failed to connect to Google Drive service.")

    file_metadata = {'name': filename, 'parents': [folder_id]}
    media = MediaIoBaseUpload(io.BytesIO(file_data), mimetype=mimetype, resumable=True)

    try:
        uploaded_file = drive_service.files().create(
            body=file_metadata,
            media_body=media,
            fields='id, webContentLink, name, mimeType'
        ).execute()
        return uploaded_file
    except HttpError as e:
        logger.error(f"❌ Drive API upload failed: {e.content.decode()}")
        raise HttpError(e.resp, f"Failed to upload file: {e.content.decode()}".encode('utf-8'))
    except Exception as e:
        logger.error(f"❌ Unexpected error during file upload: {e}")
        raise Exception(f"Internal error during upload operation: {e}")
