# -*- coding: utf-8 -*-
"""Firestore Test Data Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSejVNvRh4emV1gJEMCVhD1wu4LaqhDa
"""

import os
import json
import logging
from firebase_admin import initialize_app, firestore
from firebase_admin import credentials

# --- Configuration ---
TEST_CASE_ID = "TEST-CASE-001"
COLLECTION_NAME = "cases"

# A tiny, placeholder image (a single red pixel) in Base64
# The Python backend needs this string to be valid.
PLACEHOLDER_BASE64_IMAGE = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyBlAAAAHElEQVQI12P4//8/w38GIAXDTAgFMABiigJ2GgT+AAAAAElFTkSuQmCC"

# --- Test Document Data (Structured as required by report_generator.py) ---
TEST_DOCUMENT_DATA = {
    # General Report Metadata
    "customer_type": "INDIVIDUAL",
    "photo_analysis_description": "Liveness check passed. Face match confidence: 99.8%. No tampering detected.",
    "id_document_file": "dl_scan.jpg",
    "address_document_file": "utility_bill.pdf",
    "bank_document_file": "bank_statement.pdf",
    "abn_document_file": "", # Not applicable for INDIVIDUAL test case

    # CRITICAL: Data fields used to populate the tables on Page 1
    "extracted_fields": [
        {"field": "licence_number", "value": "350015"},
        {"field": "date_of_birth", "value": "11 Jan 1990"},
        {"field": "expiry_date", "value": "18 Apr 2028"},
        {"field": "address", "value": "15 BUCHANAN RISE, COOGEE WA 6166"},
        {"field": "issue_date", "value": "20 JAN 2025"},
        {"field": "account_name", "value": "G & DM POP"},
        {"field": "bsb", "value": "012-345"},
        {"field": "account_number", "value": "678912345"},
        {"field": "statement_period", "value": "60 DAYS"},
    ],

    # CRITICAL: Attachments array used to populate the images on Page 2
    "attachments": [
        {
            "type": "POI",
            "fileName": "id_scan.jpg",
            "data_uri": PLACEHOLDER_BASE64_IMAGE,
            "metadata": {
                "filename": "id_scan.jpg",
                "type": "POI",
                "status": "PASS",
                "confidence": "99%",
                "date": "2025-12-12",
                "status_class": "status-pass"
            }
        },
        {
            "type": "POA",
            "fileName": "bill_2025.pdf",
            "data_uri": PLACEHOLDER_BASE64_IMAGE,
            "metadata": {
                "filename": "bill_2025.pdf",
                "type": "POA",
                "status": "PASS",
                "confidence": "95%",
                "date": "2025-12-12",
                "status_class": "status-pass"
            }
        },
        {
            "type": "SOF",
            "fileName": "bank_statement.pdf",
            "data_uri": PLACEHOLDER_BASE64_IMAGE,
            "metadata": {
                "filename": "bank_statement.pdf",
                "type": "SOF",
                "status": "REVIEW",
                "confidence": "90%",
                "date": "2025-12-12",
                "status_class": "status-review"
            }
        }
    ]
}

def insert_test_document():
    """Initializes Firebase and inserts the test document."""
    try:
        # Check for local credentials needed for Admin SDK
        if not os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
            logging.error("GOOGLE_APPLICATION_CREDENTIALS environment variable is NOT set.")
            logging.error("Please set it to the path of your service account JSON file before running.")
            return

        # Initialize the Admin SDK (it finds credentials automatically)
        initialize_app()
        db = firestore.client()
        logging.info("Firebase Admin SDK initialized successfully.")

        # Set the document
        doc_ref = db.collection(COLLECTION_NAME).document(TEST_CASE_ID)
        doc_ref.set(TEST_DOCUMENT_DATA)

        logging.info(f"✅ SUCCESSFULLY inserted document: {COLLECTION_NAME}/{TEST_CASE_ID}")
        logging.info("You can now test the report endpoint with this ID.")

    except Exception as e:
        logging.error(f"Failed to insert test data: {e}", exc_info=True)
        logging.error("Ensure your service account has 'Firestore User' permissions.")


if __name__ == "__main__":
    insert_test_document()